### ISSUE TITLE
[Feature]  SDK - Get Single Feature

### ISSUE THREAD

**Issue by U001264** [growthbook/growthbook#1607]
### Description of Feature

We are using the growthbook in our company, and the number of 'features' is growing a lot. We are using 'sdk csharp' to communicate with Growthbook, and we noticed a limitation in the features search, where we only have the possibility to retrieve ALL the features at once (/api/features/{sdk-key}) and we don't have the possibility to search a single feature.
This could generate a problem with the size of the payload returned in the future due to the number of existing features in the environment.
 
We tried to use growthbook core apis like (https://growthbook-api.domain.com.br/feature/feature-name), but it requires a JWT Token and we didn't see any possibility to generate a JWT in the UI as well as how can we generate an API SECRET (SDK SECRET), that is, the JWT is linked only to an authenticated user?.

So do we have any doubts?
-  Which is the best route??
    Create a service user? authenticate the user through 'auth/login' and use this JWT for the next request?
Or, is there any way to access these apis without a JWT? Using something like api-secret.

**Comment by bryce-fitzsimons** [comment]
There currently is no way to query an SDK key for a specific feature using the `/api/features/{sdk-key}` endpoint, and I don't foresee that changing. Having predictable payloads allows us to implement various levels of caching more efficiently (in-app, CDN, proxy, in-SDK). You also wouldn't want to use the core APIs since they do not return the feature data in an acceptable format for SDK use.

Instead, your best bet is probably segmenting your SDK Connections (SDK keys) by project and tagging features to specific projects.
