### ISSUE TITLE
[Bug] Cannot read properties of undefined (reading '_ctx') 

### ISSUE THREAD

**Issue by sidagwl228** [growthbook/growthbook#1637]
### Summary

When using "**getFeatures**" function from "**useGrowthBook**" hook, I get an error list above (getting same issue with all other functions as well). But if I try to use the same function using the growthbook instance instead, it works perfectly.

Seems like the issue is with "this" value being undefined. when accessed from the "useGrowthBook".

![image](https://github.com/growthbook/growthbook/assets/136440585/12e6a095-2f63-45bb-b318-70fc14cf5608)

#### Expected Behavior

Upon calling "getfeatures" function from  "useGrowthBook" hook, it should work perfectly fine.

#### Current Behavior

When using "getFeatures" function from "useGrowthBook" hook, I get error "Cannot read properties of undefined (reading '_ctx') ".

**Comment by tinahollygb** [comment]
Do you have the `<GrowthBookProvider>` in your app? You will need to implement it in order to use the hooks. Here are some examples: [react-native](https://github.com/growthbook/examples/blob/main/react-native-cli/App.tsx#L120), [Next.js](https://github.com/growthbook/examples/blob/main/next-js/pages/_app.tsx#L57).

**Comment by jdorn** [comment]
Closing this issue as solved.  If this is still a problem, please open a new issue.
