### ISSUE TITLE
[Bug] Cannot pull data from intraday tables on `__rawExperiment`

### ISSUE THREAD

**Issue by gigazine-dev** [growthbook/growthbook#1757]
### Summary

I tried the A/A test using GA4 and BigQuery but no data was shown.

I copied & pasted SQL to BigQuery: 
![snap3979](https://github.com/growthbook/growthbook/assets/43030702/0884224e-488f-474e-8ac3-2d9ea8f3b928)
Result:
> 表示するデータはありません(No data to display)

After adding intraday tables to WHERE, it works well.
![snap3978](https://github.com/growthbook/growthbook/assets/43030702/9d118fee-2da1-47bf-8664-072dcbc561d6)

#### Expected Behavior

Users can use intraday tables for experiments.

**Comment by lukesonnet** [comment]
We used to not automatically support including intraday tables with our auto-generated queries for GA4. We now do, so you're seeing this because you set up your data source in an old version of GrowthBook.

When did you set up this datasource? We landed the change last month to include intraday tables by default (https://github.com/growthbook/growthbook/pull/1673). If you're self-hosting then it will be in version 2.5 or in `latest` as of a month ago.

To fix the issue in your case, you can either:
* recreate the datasource and metrics and they should automatically include the intraday tables (seems painful to me)
* Edit your "Experiment Assignment Query" in your data source as well as editing the SQL for your Metrics to basically add that OR clause. You'll basically need to change the date filter just as you suggest, from `(_TABLE_SUFFIX BETWEEN '{{date startDateISO "yyyyMMdd"}}' AND '{{date endDateISO "yyyyMMdd"}}')` to `WHERE ((_TABLE_SUFFIX BETWEEN '{{date startDateISO "yyyyMMdd"}}' AND '{{date endDateISO "yyyyMMdd"}}') OR
 (_TABLE_SUFFIX BETWEEN 'intraday_{{date startDateISO "yyyyMMdd"}}' AND 'intraday_{{date endDateISO "yyyyMMdd"}}'))`

You can always tweak our default queries in this way to suit your purpose.
