### ISSUE TITLE
Use clickhouse instead of Mongo as backend storage?

### ISSUE THREAD

**Issue by Slach** [growthbook/growthbook#18]
Could you think about using ClickHouse instead of MongoDB?
Please look to http://clickhouse.yandex/docs/en/
ClickHouse is a blazing fast Columnar database, which contains scale-out cluster data models

**Comment by jdorn** [comment]
MongoDB is only used to store metadata and cached query results.  The actual raw experiment and metric data can be stored in Redshift, BigQuery, Snowflake, or a few others. I think it definitely makes sense to add ClickHouse to that list of supported data sources.

I'm not too familiar with ClickHouse.  Are there any major limitations compared to the other big columnar databases that might make it difficult to support?  We don't use window functions, so that makes things easier I think.

**Comment by Slach** [comment]
clickhouse even support p-value calculation https://clickhouse.tech/docs/en/sql-reference/aggregate-functions/reference/studentttest/
