### ISSUE TITLE
[Bug] Incorrect "In Progress Conversions" behavior with ratio metrics that have different conversion windows

### ISSUE THREAD

**Issue by jdorn** [growthbook/growthbook#1844]
### Summary

If the numerator and denominator of a ratio metric have different conversion windows, we currently only use the numerator when determining the cutoff for "Exclude In Progress Conversions".  We should instead of use MAX of the numerator and denominator's conversion windows.

**Comment by august-growthbook** [comment]
More info from the customer:

Hi ­@Jeremy Dorn,
I’m not sure what you wrote in the ticket describe what I meants.

I try to put it more clearly:
I want my user to fulfill the whole funnel to be counted when I am in exluded in progress conversions,

In my example if my ratio is 100 / 1000 but both events have different conversion windows, I am quite convinced that each metric is computed on its own conversion window and not further selection is performed where only users who completed both conversion windows should be part of the final computation.

currently If i compare 2 funnel metrics :
• metric A / metric B
• metric C / metric B
with conversion windows
metric A = 2 days
metric B = 1 day
metric C = 5 days

I might have :
• metric A / metric B = 10/100
• metric C / metric B = 5 / 100
because metric B is computed with the same conversion window (1day) in both cases
