### ISSUE TITLE
[Bug] Percentile capping is working improperly in Clickhouse

### ISSUE THREAD

**Issue by ndubitsk** [growthbook/growthbook#1881]
### Summary

Percentile capping is using the function `quantileDeterministic` in Clickhouse. The results of this function are `null`, so further calculations are invalid.
Maybe you can switch to another function, for example, `qunatileExact`/`quantile`.
Link to the bug in Clickhouse: https://github.com/ClickHouse/ClickHouse/issues/35317

#### Expected Behavior

After applying percentile capping, results are capped by the value that is set in the metric's settings (Query Settings -> Cap User Values? -> Percentile capping).

#### Current Behavior

After applying percentile capping, results are incorrect (metrics are equal to 0), because of the `quantileDeterministic` function.

**Comment by lukesonnet** [comment]
Thanks for reporting this, obviously in my testing I didn't hit the same limit you're hitting. I think I'd still prefer to use `quantileDeterministic` if possible, for performance and reproducibility reasons, but I'll have to investigate.

**Comment by and-kul** [comment]
@lukesonnet here is the line of code, producing a bug:
https://github.com/growthbook/growthbook/blob/46ec3494a6ea3f9016eb2a8f683708e04dbcb565/packages/back-end/src/integrations/ClickHouse.ts#L95

The problem is that passing a constant like `1234` (seed) for **determinator** is not a proper way to use `quantileDeterministic` function, like it was explained [here](https://github.com/ClickHouse/ClickHouse/issues/35317#issuecomment-1073315248)
