### ISSUE TITLE
[Bug] Streaming Updates doesn't work properly with streamingHost property

### ISSUE THREAD

**Issue by davidtaboas** [growthbook/growthbook#1965]
### Summary

Setting streamingHost property is not working properly with the streaming updates because of this line

https://github.com/growthbook/growthbook/blob/e1f2314ad397645df955182fb43c1ef2765c75b5/packages/sdk-js/src/feature-repository.ts#L407

#### Expected Behavior

The sse support should be checked against streamingHost, not apiHost

#### Current Behavior

The sse support is using the apiHost although streamingHost is set

**Comment by bryce-fitzsimons** [comment]
Can you please provide more information about your setup, both from an SDK and networking standpoint? We intended that the `apiHost` would be responsible for setting the `"x-sse-support"` header. If the header is present, it means: SSE is supported, go ahead and try to establish a streaming connection.

**Comment by dlemaigl** [comment]
We understand that if we specify a _streamingHost_ the check if it is possible to use SSE should be done against that URL and not against _apiHost_.

In our case the _apiHost_ URL does not support _SSE_, we want to use it only to serve the static JSON of the SDKs, and the _streamingHost_ URL is the one in charge of serving those SSE.

If we send the "x-sse-support" header from _apiHost_ we would be lying because in that URL it is not supported.

**Comment by bryce-fitzsimons** [comment]
I understand the confusion, but we didn't design it to work that way. Basically, _apiHost_ is the main delegator or decider about whether or not streaming is allowed (either on itself or on _streamingHost_). When the SDK first handshakes with GrowthBook, it's on the `/api/features/sdk-xxx` endpoint (apiHost). It will hydrate down the features as well as inform the SDK that "everything is ok for streaming". If we did the `x-sse-support` check on the _streamingHost_ instead, then we'd need an additional hop before starting streaming.

**Comment by bryce-fitzsimons** [comment]
Closing this issue, but feel free to reach out if you'd like to discuss more.

**Comment by bryce-fitzsimons** [comment]
https://github.com/growthbook/growthbook-flutter/commits/main/
