### ISSUE TITLE
[Bug]  Visual Editor Plugin Auto Adding Cursor Styles 

### ISSUE THREAD

**Issue by MobMuseumDevTeam** [growthbook/growthbook#2201]
### Summary

When changes are made in the Visual Editor to the Style attributes a "cursor: move" is automatically added to whatever has been edited. 

#### Expected Behavior

When I make a small change like a background color or something, I would expect my mouse cursor to continue to be a pointer like normal. 

![image (9)](https://github.com/growthbook/growthbook/assets/88806299/a0eeab00-88e3-4d5a-bbfa-4089b70aa4a6)

#### Current Behavior

Any changes in the visual editor make the edited section have a the much larger and strange looking "move cursor".  

![image (8)](https://github.com/growthbook/growthbook/assets/88806299/8cd3a4bc-6f4f-4b88-b31a-94eb735ca454)

**Comment by bttf** [comment]
Hi @MobMuseumDevTeam This is because we allow drag-and-drop'ing elements that are selected by the editor. When changing the background color, this requires an element to be selected, which leads to this behavior. You can always de-select the element by clicking outside of it, or switching to 'Interactive mode' (the arrow symbol on the toolbar).
