### ISSUE TITLE
customization vs. config yaml

### ISSUE THREAD

**Issue by benbenbang** [growthbook/growthbook#268]
Hi there 👋🏻 

We are planning to do a POC with GB.
I have a few questions regarding setting the `config.yml`

### Info
image version: `git-0faaf6f`

### Questions
1. If I build the docker image with setting our **pre-defined data warehouse**, it seems that we won't be able to add new sources and update the metrics from the UI anymore?
2. Following Q1, if it's the case, any blocker to implementing a way to let users reuse the connections but with a different/flexible schema? It's a bit tedious to keep redefining the data sources. 
3. Following Q1, if it's the case, can we at least make the metrics part to be configurable from the UI. It's not scalable and not easy to use if we have them hardcoded in the YAML.
4. Any plan to integrate SSO? e.g. Okta?

For 1 - 3, maybe I missed some important doc about the best practices of using GB. Could you please kindly share how should we configure it with more flexibility but in a secure way.

Thanks for all the help.

**Comment by jdorn** [comment]
Hi!  Typically, a company will just have a single data source.  I'm curious about your use case for needing multiple sources?

And yes, if you use config.yml you won't be able to create or modify metrics in the UI anymore.

We usually recommend not using config.yml when you are first setting GrowthBook up since things often change frequently during that stage and being able to use the UI makes it much simpler to manage.  Once you start using GrowthBook in production and everything is stable, you can easily export all of your settings to a config.yml file.  At that point, adding metrics or tweaking settings will be a fairly rare event that you probably want to be version controlled and code reviewed anyway.

For SSO (Okta), we do plan to support that for self-hosted installations, but we're still figuring out specifics.

**Comment by benbenbang** [comment]
Hello @jdorn,

Thanks for the clarification, for the `config.yml` part. Maybe using the app in two environments indeed makes more sense now.

About your questions for the data source, it's also related to my first question. That's true that we only have one analytics database. But to aggregate tracking, product, and user info, the source needs to access multiple schemes in the DB.

I wonder if there is a flexible way to define a source without a fixed schema so that we can choose a different schema in the query. 


Thanks

**Comment by benbenbang** [comment]
ahh nice, I thought it's similar to Redash, i.e. it's fixed after we defined the schema. Good to hear it works in this way. Thanks for all the help. Closing this issue 🙏🏻
