### ISSUE TITLE
cdn.growthbook.io IP address range

### ISSUE THREAD

**Issue by gabrielmaldi** [growthbook/growthbook#397]
Hi!

Some of our clients have strict networking restrictions and whitelist by IP address instead of domain name.

We need to enable requests to `cdn.growthbook.io` and I was wondering if there is an IP address range I can tell them to whitelist; I currently see `52.85.213.45` as the IP address but I guess that's probably only applicable to my geographical region?

Thanks!

**Comment by jdorn** [comment]
Yeah, we use CloudFront which doesn't support static IP addresses. What I recommend doing is adding your own caching layer within the client's infrastructure. So instead of loading from our CDN you would load from redis or S3 or similar.

We have an [API](https://docs.growthbook.io/app/api) and [webhooks](https://docs.growthbook.io/app/webhooks) to keep your cache up to date.

**Comment by gabrielmaldi** [comment]
Will look into that. Thanks!
