### ISSUE TITLE
New C# SDK

### ISSUE THREAD

**Issue by darklordzw** [growthbook/growthbook#420]
I just published a C# version of the SDK to the NuGet package repository.

- NuGet link: https://www.nuget.org/packages/growthbook-c-sharp/ 
- GitHub repo: https://github.com/darklordzw/growthbook-c-sharp 

It only has one package dependency, Newtonsoft.JSON, the ubiquitous C# JSON library. The SDK targets .NET Standard 2.0, which should allow it to be used with ASP.NET, Windows apps, and Unity.

If it looks good, would you add it to the list of SDKs on your site?

Thanks!

**Comment by Mastermindzh** [comment]
Hey @darklordzw,

You should probably consider abstracting away Newtonsoft so that users can use the much newer (and faster) [System.Text.Json](https://docs.microsoft.com/en-us/dotnet/api/system.text.json?view=net-6.0).

The company I work for hasn't decided on a specific product yet but if we go for Growthbook I'd be more than happy to assist you with some of the code.

Some ideas to increase code quality from my quick scroll trhrough:

- Abstractions on the serializer
- Use global usings
- Add validations/restrictions on properties (f.e Start/End for the namespace)
- Some code in the Utilities file has a pretty high complexity rating
- Usage documentation (apart from linking to the provided examples)
- Add an editorconfig
- Add dotnet-format

Good luck, let's hope a .net package doesn't take too long to get published !

**Comment by darklordzw** [comment]
Hi @Mastermindzh,

Thanks for the suggestions! Let me know if your company decides to go with Growthbook, any contributions would be appreciated.

The package using Newtonsoft is published and ready to use: https://www.nuget.org/packages/growthbook-c-sharp/. The repo has moved to become part of the main Growthbook project, here's the new URL: https://github.com/growthbook/growthbook-c-sharp.

I'll take a look at integrating your suggestions in an upcoming release.

**Comment by Mastermindzh** [comment]
Nice, well done on getting your package accepted!

If we go with growthbook we'll definitely start contributing.
We're using System.text.json and have already converted a few other packages to it (with abstractions)
