### ISSUE TITLE
[Feature] Add SQL validation to all forms we enter SQL

### ISSUE THREAD

**Issue by tinahollygb** [growthbook/growthbook#542]
### Description of Feature

Add SQL validation to help users validate their SQL queries.

This feature has the following benefits:

- users may have more confidence in their queries
- validation tooling can help handhold users, which can be beneficial for more complex queries

**Comment by jdorn** [comment]
I can't find any existing SQL validator libraries that would work for our use case. The closest is probably pythons `sqlfluff` library, but that seems like it mostly enforces linting rules like whitespace and is not meant as a syntax checker (though it might still work)

There also doesn't seem to be any library that checks to make sure required columns are being selected.

I propose 3 layers of validation:
1. Write some simple regex validation ourselves to catch common errors like forgetting to select required columns
2. Try implementing sqlfluff and see if it can help catch more complicated syntax errors like mismatched parentheses
3. Run the queries against the data source with a `limit 1` clause and check that the right column names are returned and the data types look correct

All are useful in their own ways. We can do 1 first, since it's easy, and then iterate and do the others in follow up PRs.

**Comment by lukesonnet** [comment]
@tzjames, just as part of our ongoing efforts to clean up issues, can you take a look at this and decide whether it should be closed or put on the roadmap, along with any more recent context?

**Comment by tzjames** [comment]
1 and 3 are implemented.  And with the debug view where we show the line of the error from running the actual query, I think we are good on debugging sql without sqlfluff
