### ISSUE TITLE
[Bug] Dark Mode UI bugs

### ISSUE THREAD

**Issue by tinahollygb** [growthbook/growthbook#604]
Please add any dark mode bugs here.

### Experiments table missing background colour

Solution would be to add a missing class name that applies this everywhere (e.g. `gb_table/gb-table`) or add `background-color: var(--surface-background-color);` to the default Bootstrap `table` class.

<img width="1022" alt="image" src="https://user-images.githubusercontent.com/113377031/194116543-314167b8-bf43-4eb7-93fe-cd4f8f6734c7.png">

**Comment by tinahollygb** [comment]
FYI starting fixes on this branch: https://github.com/growthbook/growthbook/tree/bug/604-dark-mode

If there are any high priority fixes we can prioritize merging this. I was going to batch them.

**Comment by jdorn** [comment]
Pagination bug:
![image](https://user-images.githubusercontent.com/1087514/194126667-8ce837b7-3478-4d04-8602-df05f32d578c.png)
Used on bottom of feature list and a few other places.

Not related to dark mode, but there's a z-index bug when there are draft feature changes on mobile and you open the left nav:
![image](https://user-images.githubusercontent.com/1087514/194127641-bf4c17e9-430a-4bd5-aece-2f5cba4a4bf3.png)

Also not dark mode related, but overflow bug on data source pages.  Only happens when there are exactly 7 or 8 lines in the SQL:
![image](https://user-images.githubusercontent.com/1087514/194127846-9bed58d9-edc0-4b1e-a2cb-2adc2e549bc2.png)

Another z-index bug for assignment queries.  Only happens where there are more than 8 lines in the SQL:
![image](https://user-images.githubusercontent.com/1087514/194128049-b29b5dfc-966c-4353-b508-9018d8ad01b7.png)

**Comment by jdorn** [comment]
### 1. Add a new InlineCode component

Make a new `<InlineCode>` component that uses Prism for syntax highlighting (like the `<Code>` component), but is meant to be shown inline with text.  So no copy/expand buttons, less padding, transparent background, etc.. This should be used on the Feature page when we show JSON feature values and advanced conditions.

![image](https://user-images.githubusercontent.com/1087514/194638123-397d906b-dbe8-4490-89ab-e43a6593a3e1.png)

### 2. Update styles for Code component

For the non-inline `<Code>` components, we want to make them visually stand out from the page more.  Maybe we always render them in dark-mode, or add a header with the language and copy/expand buttons, or line numbers.  Something that makes them stand out and not look like the rest of the page text.

For reference, this is how the current code component looks:

![image](https://user-images.githubusercontent.com/1087514/194637562-4f5d198c-ec4d-43f3-8922-51a3316d1817.png)

Here's an example from Sentry's docs:

![image](https://user-images.githubusercontent.com/1087514/194638284-b36134eb-071b-4f96-bb0b-5379a12871c5.png)

Here's one from Twilio:

![image](https://user-images.githubusercontent.com/1087514/194638608-fa3ea13f-4968-49eb-949b-32658eea85e2.png)

Here's MDN in light mode:

![image](https://user-images.githubusercontent.com/1087514/194638840-2200107b-fdea-4143-9a8b-b46f9cb8bb3f.png)

And MDN in dark mode:

![image](https://user-images.githubusercontent.com/1087514/194638900-31413f11-4d03-405a-84ac-ad48f3ab9e0b.png)

**Comment by jdorn** [comment]
I fixed many of the above bugs in #618 
- The InlineCode / Code styling bugs
- Overflow and z-index bugs for assignment queries

**Comment by Auz** [comment]
The experiment list page now lacks a border in light mode (I think we could just add the appbox class to it).
<img width="176" alt="Screen Shot 2022-10-11 at 1 34 16 AM" src="https://user-images.githubusercontent.com/46107/195040499-2d7aa7be-d202-464b-8540-e525b042e25e.png">

The dark mode colors for winning and losing highlighting don't look so great, and don't match the graph colors. 
<img width="452" alt="Screen Shot 2022-10-11 at 1 41 23 AM" src="https://user-images.githubusercontent.com/46107/195042081-2128f322-d1ef-4268-a0d9-e08fa0a7806f.png">
I suggest we use #0a4947 for the 'green', #505518 for the 'yellow', and #4f1b1b for the 'red' on dark mode

**Comment by jdorn** [comment]
The MultiSelectField font color when typing is hard to read
![image](https://user-images.githubusercontent.com/1087514/195077033-6f748c46-2b14-4252-beca-0a04fd7ca043.png)

Also, the MultiSelectField should not override the background/text color when used for tags since the colors can be customized by users and are used for organization.

Current behavior:
![image](https://user-images.githubusercontent.com/1087514/195077687-623e6e51-54ee-403c-b570-070c11ad432f.png)

Expected behavior:
![image](https://user-images.githubusercontent.com/1087514/195077882-d3abab0f-b7bb-48f2-9b58-40ab16be8626.png)

To reproduce, go to Settings -> Tags, add a few tags with custom colors.  Then add those tags to a metric and use the "Filter by tags" input on the metric page.
