### ISSUE TITLE
[Bug] Incorrect experiment results when metrics contain `null` values

### ISSUE THREAD

**Issue by jdorn** [growthbook/growthbook#725]
### Summary

If a metric value contains `null`s for some users, they will be ignored when doing `mean` and `stddev` in SQL, but will be included when doing `count`.  There are places in our code where we calculate the "sum" as `mean * count`, which will be incorrect in this case and cause our statistics engine to give incorrect results.

To solve, in the `__userMetric` CTE, we should use coalesce:

```sql
SELECT
  d.variation,
  d.dimension,
  d.${baseIdType},
  coalesce(${aggregate}, 0) as value
```

**Comment by lukesonnet** [comment]
This could also be the cause of some of the negative variances we are seeing in ratio metrics, because the null values will be differentially dropped across `VAR_SAMP(m.value)`, `VAR_SAMP(d.value)`, and `COVAR_SAMP(m.value, d.value)` if values are null in only one of the two metrics. If that is the case, then you are computing variance and covariance across different samples of users.

I'm fairly certain the above coalesce would also resolve this issue (assuming, of course, that we can safely set NULL to 0).
