### ISSUE TITLE
Integrate Matomo Analytics as Data Source

### ISSUE THREAD

**Issue by Grienauer** [growthbook/growthbook#86]
Matomo is an Open Source competitor to Google Analytics. https://matomo.org/

It would be awesome to have an integration to it because Matomo is GDPR Friendly like GrpwthBook if self-hosted and so no opt-in is needed.

Documentation: https://developer.matomo.org/guides/reporting-introduction

**Comment by jdorn** [comment]
GrowthBook does support MySQL as a data source, so one option is pointing it directly at the Matomo database.  I'm not too familiar with the database schema they use, but it should be compatible.

We try to avoid API-level integrations when possible since they are usually much more limiting than direct database queries and harder to maintain (e.g. they usually don't return a standard deviation so we can't do proper statistics)

**Comment by joecot** [comment]
Adding a quick guide in the docs on using Matomo as a data source would probably go a long way. Growthbook looks like it provides great A/B testing, but if you have to bring your own analytics to use it, Matomo seems like it'd be the least painful way to do so.

**Comment by iparker** [comment]
I'm also interested to use growthbook with matomo. Does anyone has experience how to set up a simple example with grothbook and matomo?

I think its necessary to understand the matomo-database-schema (https://developer.matomo.org/guides/database-schema) for this to integration the matomo-database as source and also the different metrics.

**Comment by Amantel** [comment]
Second this. Matomo is great and having an easy way to use it (or at least a guide) will be great.
