### ISSUE TITLE
[Bug] no API response update after adding/removing variants

### ISSUE THREAD

**Issue by Kobe** [growthbook/growthbook#971]
Summary

If in out self-hosted GrowthBook instance (latest docker image) we experienced a bug in the API feature endpoint. If you add/remove a variant (string value) the API response is not update. But if you change other settings like "default value", then it API response reflects the right amount of variants.

Expected Behavior

API endpoint reflects the current state of the configuration after each kind of changes.

Current Behavior

API endpoint only reacts on certain changes but variant addition/removal.

**Comment by jdorn** [comment]
The API feature endpoints are scoped to a specific environment.  If you remove a variant from a feature rule in dev, for example, the API endpoint for production will not get updated.  Does that explain what you're seeing or do you think something else is going on?

**Comment by Kobe** [comment]
Yes, I know. It can only reproduced on our PRO instance. Maybe it's related to the whole experimentation setup?!

`
{
"status": 200,
"features": {
"local-697": {
"defaultValue": true
},
"local-717": {
"defaultValue": "A",
"rules": [
{
"variations": [
"A",
"B",
"C",
"D"
],
"coverage": 1,
"weights": [
0.25,
0.25,
0.25,
0.25
],
"hashAttribute": "tracking_id"
}
]
},
"uds-4195": {
"defaultValue": false,
"rules": [
{
"condition": {
"url": {
"$ne": "https://mein.idealo.de/pricealerts/"
}
},
"force": false
},
{
"variations": [
false,
true
],
"coverage": 1,
"weights": [
0.5,
0.5
],
"key": "uds-4195",
"hashAttribute": "tracking_id"
}
]
},
"local-671": {
"defaultValue": true
},
"bug_reproduction": {
"defaultValue": "baz",
"rules": [
{
"variations": [
"foo",
"baz"
],
"coverage": 1,
"weights": [
0.5,
0.5
],
"key": "bug_reproduction",
"hashAttribute": "session_id"
}
]
}
},
"dateUpdated": "2023-02-01T16:08:57.565Z"
}
`

**Comment by rowolff** [comment]
The bug does not stem from the GrowthBook feature API environment feature. This bug is related to differences on two separate GrowthBook installations on two separate AWS Accounts. Our Setup:

1. AWS Account "PROD" - GrowthBook build c558f82 (2023-02-01), 3 ECS Fargate Tasks, DocumentDB cluster with 3 instances (1 primary, 2 read replica)
2. AWS Account "STG" - GrowthBook build c558f82 (2023-02-01), 1 ECS Fargate Task, DocumentDB cluster with 1 instance

On STG the behaviour is as follows. Consider a feature with 2 variants with string values, and a default
![Screenshot 2023-02-06 at 13 37 59](https://user-images.githubusercontent.com/2241551/216974077-0f2b4c89-746a-47e2-8b4f-af9ec470d91b.png)

The API will display:
```
"bug_reproduction":{"defaultValue":"foo","rules":[{"variations":["foo","bar"]...
```

Now I add a third variant "baz", save, and publish. The API will display:
```
"bug_reproduction":{"defaultValue":"foo","rules":[{"variations":["foo","bar", "baz"]
```

As expected. Now on our PROD AWS account with the same GrowthBook version, the scenario is as follows:

After setting up the feature initially:
```
"bug_reproduction":{"defaultValue":"foo","rules":[{"variations":["foo","bar"]
```

After adding "baz" it looks the same!
```
"bug_reproduction":{"defaultValue":"foo","rules":[{"variations":["foo","bar"]
```

And after changing the default value from "foo" to "bar" we get:
```
"bug_reproduction":{"defaultValue":"foo","rules":[{"variations":["foo","bar","baz"]
```

Notice that the third variant appeared, but that the default value is "foo" and not "bar" - the API is one version behind!

**Comment by rowolff** [comment]
Update: after updating to Build: [0466db4](https://github.com/growthbook/growthbook/commit/0466db4790821d98d9f659c7299906362b25a549) (2023-02-03) the issue is no longer reproducable.

**Comment by rowolff** [comment]
@jdorn  update - the issue is NOT fixed. Several colleagues at idealo are still able to reproduce it.

**Comment by RonnyBuergermeister** [comment]
I just experienced this issue, i had to do another config update to my feature to get the state i want,
so the second to last config is now available.

**Comment by jdorn** [comment]
This behavior is making me think the DocumentDB read replicas might be lagging behind the primary.  When a feature is updated, we do the following (simplified):
1. Save the updated feature to Mongo
2. Get a list of all features in the account
3. Generate a new version of the SDK payload JSON object

My hunch is that 2 is happening before the write from 1 is propagated to the read replicas and it's returning a stale version of the updated feature.

To fix this, I believe in the Mongo connection string, you can specify the write behavior to not return until the change is propagated to the read replicas.  I'm not sure if this setting is supported by DocumentDB or not, but I can look.  Alternatively, you could send all read and write traffic to a single DocumentDB instance and just keep the others around as failover in case the primary dies.

**Comment by jdorn** [comment]
Adding `?readPreference=primaryPreferred` to the Mongo connection string should fix this.  It will ensure read-after-write consistency during normal operations and fall back to eventual consistency in a failover situation.

**Comment by rowolff** [comment]
That seem to help during my testing, I'll ask my colleagues to stress test this. Thank you for the hint, @jdorn 🤗

**Comment by rowolff** [comment]
Another question: I checked the read replica lag of our secondaries and it was always around 10 .. 40ms with occasional peaks of 200ms. That doesn't explain that the API response was always exactly 1 database write behind, even minutes or hours later. How can that be the case?

**Comment by jdorn** [comment]
Yes, generating the feature payload is expensive, so in order to keep API requests fast and predictable, we generate and cache in Mongo whenever a feature changes. We can add some logic to the app to make it more tolerant of eventually consistent setups, but the only really safe way is to prefer reading from primaries because of those 200ms spikes.

**Comment by rowolff** [comment]
After testing for a few days we're good here. Feel free to close.
